# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='BookingDate',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='BuyAmount',
            new_name='buy_amount',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='BuyCurrency',
            new_name='buy_currency',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='Rate',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='SellAmount',
            new_name='sell_amount',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='SellCurrency',
            new_name='sell_currency',
        ),
    ]
