# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20160711_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='sell_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency'),
        ),
    ]
