# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_auto_20160712_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='buy_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sell_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_currency', to='currencies.Currency'),
        ),
    ]
